#spring:
 # application:
 #   name: customer-service
#  cloud:
#    config:
#      uri: http://localhost:8081
#      username: root
#      password: s3cr3t
#  boot:
#    admin:
#      client:
#        url: http://localhost:8086

server:
  port: 8085
spring:
  application:
    name: customer-service
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/