#spring:
#  application:
#    name: shopping-service
#  cloud:
#    config:
#      uri: http://localhost:8081
#      username: root
#      password: s3cr3t
#  boot:
#    admin:
#      client:
#        url: http://localhost:8086
        
server:
  port: 8084
spring:
  application:
    name: SHOPPING-SERVICE
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
      
      